/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.photoplaza.agc.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType PhotoTable.
 *
 * @since 2021-08-17
 */
@PrimaryKeys({"PhotoID"})
@Indexes({"photoID:PhotoID"})
public final class PhotoTable extends CloudDBZoneObject {
    private String PhotoID;

    private String UserID;

    private String UserName;

    private String URL;

    private String PhotoName;

    private Date CreateTime;

    @NotNull
    @DefaultValue(booleanValue = true)
    private Boolean SubFlag;

    public PhotoTable() {
        super(PhotoTable.class);
        this.SubFlag = true;
    }

    public void setPhotoID(String PhotoID) {
        this.PhotoID = PhotoID;
    }

    public String getPhotoID() {
        return PhotoID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public String getUserID() {
        return UserID;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getUserName() {
        return UserName;
    }

    public void setURL(String URL) {
        this.URL = URL;
    }

    public String getURL() {
        return URL;
    }

    public void setPhotoName(String PhotoName) {
        this.PhotoName = PhotoName;
    }

    public String getPhotoName() {
        return PhotoName;
    }

    public void setCreateTime(Date CreateTime) {
        this.CreateTime = CreateTime;
    }

    public Date getCreateTime() {
        return CreateTime;
    }

    public void setSubFlag(Boolean SubFlag) {
        this.SubFlag = SubFlag;
    }

    public Boolean getSubFlag() {
        return SubFlag;
    }

}
