/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agc.photoplaza.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType CouponTable.
 *
 * @since 2021-09-01
 */
@PrimaryKeys({"CouponID"})
@Indexes({"CouponID:CouponID", "AllCoupons:Invite_UserID,BeInvited_UserID"})
public final class CouponTable extends CloudDBZoneObject {
    private String CouponID;

    private String Invite_UserID;

    private String Invite_UserName;

    private String BeInvited_UserID;

    private String BeInvited_Name;

    private Double Coupon_Price;

    private Date Effective_Time;

    public CouponTable() {
        super(CouponTable.class);
    }

    public void setCouponID(String CouponID) {
        this.CouponID = CouponID;
    }

    public String getCouponID() {
        return CouponID;
    }

    public void setInvite_UserID(String Invite_UserID) {
        this.Invite_UserID = Invite_UserID;
    }

    public String getInvite_UserID() {
        return Invite_UserID;
    }

    public void setInvite_UserName(String Invite_UserName) {
        this.Invite_UserName = Invite_UserName;
    }

    public String getInvite_UserName() {
        return Invite_UserName;
    }

    public void setBeInvited_UserID(String BeInvited_UserID) {
        this.BeInvited_UserID = BeInvited_UserID;
    }

    public String getBeInvited_UserID() {
        return BeInvited_UserID;
    }

    public void setBeInvited_Name(String BeInvited_Name) {
        this.BeInvited_Name = BeInvited_Name;
    }

    public String getBeInvited_Name() {
        return BeInvited_Name;
    }

    public void setCoupon_Price(Double Coupon_Price) {
        this.Coupon_Price = Coupon_Price;
    }

    public Double getCoupon_Price() {
        return Coupon_Price;
    }

    public void setEffective_Time(Date Effective_Time) {
        this.Effective_Time = Effective_Time;
    }

    public Date getEffective_Time() {
        return Effective_Time;
    }

}
